### ISSUE TITLE
the ion thruster uses liquid fuel and not electricity otherwise i like

### ISSUE THREAD

**Issue by adminGamer11234** [DinitrogenTetroxide/sfs-electricity#2]

**Comment by DinitrogenTetroxide** [comment]
The cause for that is because real-life ion thrusters don't run entirely on electricity, but also consume a bit of fuel. That was made in the game also because of another reason: Making them drain only electricity creates a weird bug, which makes them either consume electricity even when the engine is off, or not consume it at all, even when the engine is on.
